services:
  db:
    image: 'bitnami/postgresql:15'
    networks:
      - app-tier
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=bn_swappin_messages
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=bitnami_swappin_messages
  kafka:
    image: 'bitnami/kafka:4.0'
    networks:
      - app-tier
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  swappin-messages-one:
    image: halversondm/swappin-messages:latest
    networks:
      - app-tier
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=one,db
      - POSTGRESQL_USERNAME=bn_swappin_messages
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=bitnami_swappin_messages
    depends_on:
      - kafka
      - db
  swappin-messages-two:
    image: halversondm/swappin-messages:latest
    networks:
      - app-tier
    ports:
      - "9001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=two,db
      - POSTGRESQL_USERNAME=bn_swappin_messages
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=bitnami_swappin_messages
    depends_on:
      - kafka
      - db
volumes:
  kafka_data:
    driver: local
  postgres_data:
    driver: local
networks:
  app-tier:
    driver: bridge