name: Docker Image CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Code
        run: mvn -e --batch-mode clean install
      - name: Build Docker images for all Dockerfiles
        run: docker build . --tag "swappin-messages:latest"